### ISSUE TITLE
Is repo name intentionally misspelled? 

### ISSUE THREAD

**Issue by meyyappanv** [nicolaballotta/gtp3-wordpress-post-generator#1]
Hi @nicolaballotta awesome repo. Thanks for creating one. Quick question, did you intentionally misspelled? Gtp instead of gpt ? 😊

**Comment by nicolaballotta** [comment]
@meyyappanv I'm honest, I could say it was intentional, but it's not and I just noticed it 😀

At this point I would probably keep it so, since it's already linked everywhere with this url.

**Comment by nicolaballotta** [comment]
Never mind, I fixed it and Github does the proper redirect. Thanks for reporting!
