### ISSUE TITLE
The script does not see the site

### ISSUE THREAD

**Issue by guloc** [nicolaballotta/gtp3-wordpress-post-generator#2]
The script does not see the site, what could be the matter?
wordpress_blog_url = None

**Comment by nicolaballotta** [comment]
@guloc can you please share more details? did you set the environment variable?

`export WORDPRESS_URL="Your WordPress xmlrpc URL"`

**Comment by guloc** [comment]
I installed everything according to the instructions, but I  windows. Perhaps because of this error. In general, the library started working only with the help of these edits.


class Gpt3Wordpress:
    def __init__(self, api_key: str, blog_url: str, username: str, password: str):
        api_key = "MY KEY"
        openai.api_key = api_key
        blog_url = "MY URL"
        self.blog_url = blog_url + "/xmlrpc.php"
        self.username = username
        self.password = password

**Comment by nicolaballotta** [comment]
@guloc yeah I got it now, Windows has a different way to set environment variables, so you should not use the export way. You can Google how to set environment variables in Windows and that should fix the issue.

The other option is to use the `--wordpress-blog-url` option from the command line.

One last option (which I strongly suggest) is to use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) on your Windows installation. That gives you a complete Linux system, where you can run this code without any problem.
